### ISSUE TITLE
New scripts overwirte old ones

### ISSUE THREAD

**Issue by Cuyoya** [300f20t/Recipe-Generator#1]
New scripts generated overwrite old ones when the game or world is reloaded, starting with "generated0.zs". Have to deposit all previous scripts into a subfolder in /scripts to prevent this. Noticed this while removing some recipes.

Edit: Sorry, also to include is I'm working with the Alpha 0.1.0 Forge release

**Comment by 300f20t** [comment]
I'll work on fixing it.

**Comment by 300f20t** [comment]
I think I fixed it in the new version.
https://modrinth.com/mod/just-ctgui/version/0.1.3
https://modrinth.com/mod/just-ctgui/version/8BICqZ9l
