### ISSUE TITLE
v0.1.3 Forge, Duplicate Scripts

### ISSUE THREAD

**Issue by Cuyoya** [300f20t/Recipe-Generator#2]
While running v0.1.3 Forge, it seems to output double of every script. Not a huge issue, can just delete every other one, but figured I'd let you know. Thanks!

Ah, found this seems to happen if I don't enter a file name specifically, too.

**Comment by 300f20t** [comment]
I fixed this in version 0.1.4. It will be available in the public soon.

**Comment by 300f20t** [comment]
https://modrinth.com/mod/just-ctgui/version/Iz1y69QT
https://modrinth.com/mod/just-ctgui/version/0.1.4
